/**
 * SVG 처리 유틸리티 함수
 */

const BLOCKED_TAGS = new Set([
  "script",
  "foreignobject",
  "iframe",
  "object",
  "embed",
  "audio",
  "video",
  "canvas",
  "link",
  "style",
]);

const BLOCKED_ATTR_PREFIXES = ["on"];
const URL_ATTRS = new Set(["href", "xlink:href", "src"]);
const SAFE_DATA_URL_PREFIX = "data:image/";

/**
 * 사용자 입력 SVG를 미리보기/출력 전에 정제해 XSS 위험을 줄임
 * @param {string} code - 원본 SVG 문자열
 * @returns {string} 정제된 SVG 문자열
 */
export const sanitizeSVG = (code) => {
  if (!code || typeof code !== "string") return "";
  if (
    typeof DOMParser === "undefined" ||
    typeof XMLSerializer === "undefined" ||
    typeof NodeFilter === "undefined"
  ) {
    return "";
  }

  try {
    const parser = new DOMParser();
    const doc = parser.parseFromString(code, "image/svg+xml");
    const root = doc.documentElement;

    if (!root || root.nodeName.toLowerCase() !== "svg") {
      return "";
    }

    if (doc.querySelector("parsererror")) {
      return "";
    }

    const walker = doc.createTreeWalker(root, NodeFilter.SHOW_ELEMENT);
    const toRemove = [];
    const elements = [];

    while (walker.nextNode()) {
      elements.push(walker.currentNode);
    }

    elements.forEach((element) => {
      const tagName = element.nodeName.toLowerCase();
      if (BLOCKED_TAGS.has(tagName)) {
        toRemove.push(element);
        return;
      }

      const attrs = Array.from(element.attributes);
      attrs.forEach((attr) => {
        const attrName = attr.name.toLowerCase();
        const value = (attr.value || "").trim().toLowerCase();

        if (BLOCKED_ATTR_PREFIXES.some((prefix) => attrName.startsWith(prefix))) {
          element.removeAttribute(attr.name);
          return;
        }

        if (attrName === "style" && value.includes("url(")) {
          element.removeAttribute(attr.name);
          return;
        }

        if (URL_ATTRS.has(attrName)) {
          const isUnsafeProtocol =
            value.startsWith("javascript:") ||
            value.startsWith("vbscript:") ||
            (value.startsWith("data:") && !value.startsWith(SAFE_DATA_URL_PREFIX));
          if (isUnsafeProtocol) {
            element.removeAttribute(attr.name);
          }
        }
      });
    });

    toRemove.forEach((node) => node.remove());

    return new XMLSerializer().serializeToString(root);
  } catch {
    return "";
  }
};

/**
 * 기본 SVG 템플릿
 */
export const DEFAULT_SVG = `<svg width="24px" height="24px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<!-- Generated by Dirty Tool -->
<g id="SVGRepo_bgCarrier" stroke-width="0"></g>
<g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
<g id="SVGRepo_iconCarrier"> 
<path d="M12 22C17.5 22 22 17.5 22 12C22 6.5 17.5 2 12 2C6.5 2 2 6.5 2 12C2 17.5 6.5 22 12 22Z" stroke="#292D32" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path> 
</g>
</svg>`;

/**
 * SVG 코드를 처리하여 정리된 코드로 변환
 * @param {string} code - 원본 SVG 코드
 * @param {Object} options - 처리 옵션
 * @param {boolean} options.minify - Minify 여부
 * @param {boolean} options.currentColor - CurrentColor 모드 여부
 * @param {boolean} options.jsx - JSX 변환 여부
 * @returns {string} 처리된 SVG 코드
 */
export const processSVG = (code, options) => {
  if (!code) return "";

  let cleaned = sanitizeSVG(code);
  if (!cleaned) return "";

  // 1. Remove Comments
  cleaned = cleaned.replace(/<!--[\s\S]*?-->/g, "");

  // 2. Remove Newlines & Spaces (Simple Minify)
  if (options.minify) {
    cleaned = cleaned.replace(/\s+/g, " ").trim();
    cleaned = cleaned.replace(/>\s+</g, "><");
  }

  // 3. Remove Unnecessary Tags (Simulation)
  cleaned = cleaned.replace(/<g id="SVGRepo_bgCarrier".*?><\/g>/g, "");
  cleaned = cleaned.replace(/<g id="SVGRepo_tracerCarrier".*?><\/g>/g, "");

  // 4. Color to CurrentColor
  if (options.currentColor) {
    cleaned = cleaned.replace(/stroke="#[0-9A-Fa-f]{3,6}"/g, 'stroke="currentColor"');
    cleaned = cleaned.replace(/fill="#[0-9A-Fa-f]{3,6}"/g, 'fill="currentColor"');
  }

  // 5. JSX Conversion
  if (options.jsx) {
    cleaned = cleaned.replace(/class=/g, "className=");
    cleaned = cleaned.replace(/stroke-width=/g, "strokeWidth=");
    cleaned = cleaned.replace(/stroke-linecap=/g, "strokeLinecap=");
    cleaned = cleaned.replace(/stroke-linejoin=/g, "strokeLinejoin=");

    // Wrap in Component
    cleaned = `const IconComponent = (props) => (\n  ${cleaned.replace(/<svg/, "<svg {...props}")}\n);`;
  }

  return cleaned;
};
