/**
 * SVG 처리 유틸리티 함수
 */

/**
 * 기본 SVG 템플릿
 */
export const DEFAULT_SVG = `<svg width="24px" height="24px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<!-- Generated by Dirty Tool -->
<g id="SVGRepo_bgCarrier" stroke-width="0"></g>
<g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
<g id="SVGRepo_iconCarrier"> 
<path d="M12 22C17.5 22 22 17.5 22 12C22 6.5 17.5 2 12 2C6.5 2 2 6.5 2 12C2 17.5 6.5 22 12 22Z" stroke="#292D32" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path> 
</g>
</svg>`;

/**
 * SVG 코드를 처리하여 정리된 코드로 변환
 * @param {string} code - 원본 SVG 코드
 * @param {Object} options - 처리 옵션
 * @param {boolean} options.minify - Minify 여부
 * @param {boolean} options.currentColor - CurrentColor 모드 여부
 * @param {boolean} options.jsx - JSX 변환 여부
 * @returns {string} 처리된 SVG 코드
 */
export const processSVG = (code, options) => {
  if (!code) return "";

  let cleaned = code;

  // 1. Remove Comments
  cleaned = cleaned.replace(/<!--[\s\S]*?-->/g, "");

  // 2. Remove Newlines & Spaces (Simple Minify)
  if (options.minify) {
    cleaned = cleaned.replace(/\s+/g, " ").trim();
    cleaned = cleaned.replace(/>\s+</g, "><");
  }

  // 3. Remove Unnecessary Tags (Simulation)
  cleaned = cleaned.replace(/<g id="SVGRepo_bgCarrier".*?><\/g>/g, "");
  cleaned = cleaned.replace(/<g id="SVGRepo_tracerCarrier".*?><\/g>/g, "");

  // 4. Color to CurrentColor
  if (options.currentColor) {
    cleaned = cleaned.replace(/stroke="#[0-9A-Fa-f]{3,6}"/g, 'stroke="currentColor"');
    cleaned = cleaned.replace(/fill="#[0-9A-Fa-f]{3,6}"/g, 'fill="currentColor"');
  }

  // 5. JSX Conversion
  if (options.jsx) {
    cleaned = cleaned.replace(/class=/g, "className=");
    cleaned = cleaned.replace(/stroke-width=/g, "strokeWidth=");
    cleaned = cleaned.replace(/stroke-linecap=/g, "strokeLinecap=");
    cleaned = cleaned.replace(/stroke-linejoin=/g, "strokeLinejoin=");

    // Wrap in Component
    cleaned = `const IconComponent = (props) => (\n  ${cleaned.replace(/<svg/, "<svg {...props}")}\n);`;
  }

  return cleaned;
};

